import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "../styles/globals.css";
import AuthGate from "@/components/AuthGate";
import TopBar from "@/components/TopBar";

const inter = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jetBrainsMono.variable} antialiased`}>
        <AuthGate>
          <TopBar />
          <div className="pb-16 pt-16 md:pb-0">{children}</div>
        </AuthGate>
      </body>
    </html>
  );
}
